apiVersion: apps/v1
kind: Deployment
metadata:
    name: database
    #namespace: estack
spec:
    replicas: 1
    selector:
      matchLabels:
        role: database
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 25%
    template:
       metadata:
         labels:
           role: database
       spec:
         containers:
         - name: database
           image: mongo
           ports:
           - containerPort: 27017
           env:
             - name: MONGO_INITDB_ROOT_USERNAME
               value: admin
             - name: MONGO_INITDB_ROOT_PASSWORD
               value: admin
