apiVersion: v1
kind: Service
metadata:
   name: mongodb-svc
   #namespace: estack
spec:
   selector:
      role: database
   type: ClusterIP
   ports:
   - port: 27017
     protocol: TCP
     targetPort: 27017
