apiVersion: v1
kind: Service
metadata:
   name: backend
   #namespace: estack
spec:
   selector:
      role: backend
   ports:
   - port: 8000
     protocol: TCP
     targetPort: 8000
   type: ClusterIP
