apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend
   namespace: estack
spec:
   replicas: 1
   selector:
     matchLabels:
       role: frontend
   strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 25%
   template:
     metadata:
       labels:
         role: frontend
     spec:
       containers:
       - name: frontend
         image: edhala12345/estack-client:latest
         imagePullPolicy: Always
         env:
            - name: VITE_backend_url
              value: "http://backend:8000"
         ports:
         - containerPort: 5173
           protocol: TCP
       
          
