apiVersion: v1
kind: Service
metadata:
  name: frontend
  #namespace: estack
spec:
  selector:
     role: frontend
  type: LoadBalancer
  ports:
  - port: 5173
    protocol: TCP
    targetPort: 5173
    


   
